<header class="titulo_centro">
    <label class="titulo">Nuevo Autor</label>
</header>
<div class="clear"></div>
<div class="container_form">
    <div class="information_form">
        <label>
            Información para el ingreso de un nuevo autor.
        </label>
    </div>
    <div class="container_form_data">
        <form id="newAuthorForm" name="newAuthorForm" action="" onsubmit="return newAuthor('<?php echo $this->url(array('controller' => 'author', 'action' => 'create'), null, true); ?>')">
            <div class="form_auth_left">
                <table cellpadding="1px" cellspacing="10px"  style="padding-left: 5px;">
                    <tr>
                        <td>
                            <label>Nombre:</label>
                            <input type="text" id="name" name="name"  style="width: 190px;" placeholder="Nombre" />
                        </td>
                        <td>
                            <label>Apellido:</label>
                            <input type="text" id="last_name" name="last_name" required style="width: 190px;" placeholder="Apellido" />
                        </td>
                    </tr>

                    <tr>
                        <td colspan="2">
                            <label>Biografía:</label>
                            <textarea id="bio" name="bio" style="padding-top: 10px; width: 400px; height: 90px;" placeholder="Biografía"></textarea>
                        </td>

                    </tr>
                    <tr>
                        <td colspan="2">
                            <label>Educación:</label>
                            <textarea id="edu" name="edu" style="padding-top: 10px; width: 400px; height: 70px;" placeholder="Educación"></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td  colspan="3" style="width: 150px;">
                            <label>Lugar de nacimiento:</label>
                            <div style="width: 400px;">
                                <div id="div_pais" style="float: left; padding-right: 5px;">
                                    <select data-placeholder="Pais" id="pais" name="Pais" class="select">
                                    </select>
                                </div>
                                <script type="text/javascript">
                                    //la funcion llamada esta en el js cargar_contenido - carpeta public
                                    cargarContenido('<?php echo $this->url(array('controller' => 'location', 'action' => 'country', 'obligatorio' => '0'), null, true) ?>', 'div_pais')
                                </script>
                                <div id="div_estado" style="float: left; padding-right:5px;">
                                    <select data-placeholder="Estado"  id="estado" name="Estado" style="width: 116px;" class="select">
                                    </select>
                                </div>
                                <div id="div_ciudad"  style="float: left;">
                                    <select data-placeholder="Ciudad" id="ciudad" style="width: 116px;" name="Ciudad" class="select">>
                                    </select>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td  colspan="3" style="width: 150px;">
                            <label>Nacimiento:</label>
                            <div id="pickerDate" style="width: 400px;">
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" style="text-align: center; padding-top: 5px; padding-bottom: 5px; width: 400px; ">
                            <div style="float: right; padding-right: 100px;">
                                <fieldset id="actions">
                                    <input type="submit" id="submit" value="Ingresar">
                                </fieldset>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
        <div class="form_auth_right">
            <div class="upload_picture"></div>
            <div class="uploadButtom">
                <label>Subir Foto</label>
                <form id="imageform" method="post" enctype="multipart/form-data" action='<?php echo $this->url(array('controller' => 'upload', 'action' => 'imageupload'), null, true); ?>'>
                    <input type="file" class="uploadInput" id="photoimg" name="photoimg" style="cursor: pointer;">
                </form>
            </div>
        </div>
        <div class="clear"></div>

    </div>
    
    <div id="listAuthors" class="auth_section_right">
        <section class="gallitoCorners">
            <div class="authosList">
                <article>
                    <header>Gabriel García Márques</header>
                    <aside>(Aracataca, Colombia, 6 de marzo de 1927)</aside>
                    <p>Escritor, novelista, cuentista, guionista y periodista colombiano.
                       En 1982 recibió el Premio Nobel de Literatura. 
                       Conocido familiarmente y por sus amigos como Gabito (hipocorístico guajiro para Gabriel).</p>
                </article>
            </div>

        </section>

    </div>
    

    <script type="text/javascript" >
            
        $(function() {
            //Adding
            $(".section").addClass("section_author");
            
            $("#pickerDate").birthdaypicker({dateFormat:"bigEndian"});
            $("select").chosen();
            
            //Fixing the style
            $("#pickerDate .chzn-container").eq(0).css("padding-right","7px");  
            $("#pickerDate .chzn-container").eq(2).css("padding-left","7px"); 
            
            $('#photoimg').live('change', function()
            {
                $("#preview").html('');
                $("#preview").html('Cargando...');
                $("#imageform").ajaxForm(
                {
                    target: '.upload_picture'
                }).submit();
            });
        });
            
    </script>





</div>