<form id="form" class="newUser" onsubmit="return register('<?php echo $this->url(array('controller' => 'register', 'action' => 'new'), null, true); ?>')">
    <h1>Registro</h1>
    <fieldset id="inputsNewUser">
        <div class="column">
            <div>
                <label>Usuario:</label>
                <input id="username" data-url="<?php echo $this->url(array('controller' => 'register', 'action' => 'checkusername'), null, true); ?>" type="text" placeholder="Usuario" autofocus="" minlength="5" required=""/>
                <ul style="display: none;"> 
                    <li></li>
                </ul>
            </div>
            <div>
                <label>Clave:</label>
                <input id="password" type="password" name="password" placeholder="Clave" required="" minlength="5" />
            </div>
            <div>
                <label>Confirma Clave:</label>
                <input id="confirm_password" type="password" placeholder="Confirma Clave" data-equals="password" required=""/>
                <ul style="display: none;"> 
                    <li></li>
                </ul>
            </div>
        </div>
        <div class="column">
            <div>
                <label>Email:</label>
                <input id="email" type="email" placeholder="Email" required=""/>
            </div>
            <div>
                <label>Nombre:</label>
                <input id="name" type="text" placeholder="Nombre" required=""/>
            </div>
            <div>
                <label>Apellido:</label>
                <input id="lastname" type="text" placeholder="Apellido" required=""/>
            </div>
        </div> 
    </fieldset>
    <fieldset id="actions">
        <input type="submit" id="submit" value="Registrarme">
        <a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'login'), null, true); ?>">Ya tienes una cuenta?, Ingresa aqui</a>
    </fieldset>
</form>