<header class="titulo_centro">
    <label class="titulo">Nuevo Autor</label>
</header>
<div class="clear"></div>
<div class="container_form">
    <div class="information_form">
            <article>
                Información para el ingreso de un nuevo autor.
            </article>
    </div>
    <form name="newAuthorForm" action="" onsubmit="return newAuthor('<?php echo $this->url(array('controller' => 'register', 'action' => 'newauthorget'), null, true); ?>')">
        <div class="container_form_data">
            <table cellpadding="1px" cellspacing="10px"  style="padding-left: 5px;">
                <tr>
                    <td>
                        <input type="text" id="name" required style="width: 190px;" placeholder="Nombre" />
                    </td>
                    <td>
                        <input type="text" id="last_name" required style="width: 190px;" placeholder="Apellido" />
                    </td>
                </tr>

                <tr>
                    <td colspan="2">
                        <textarea id="bio" style="padding-top: 10px; width: 400px; height: 70px;" placeholder="Biografía"></textarea>
                    </td>

                </tr>
                <tr>
                    <td colspan="2">
                        <textarea id="edu" id="education" style="padding-top: 10px; width: 400px; height: 70px;" placeholder="Education"></textarea>
                    </td>
                </tr>
                <tr>
                    <td  colspan="3" style="width: 150px;">
                        <div style="width: 400px;">
                            <div id="div_pais" style="float: left; padding-right: 7px;">
                                <select data-placeholder="Pais" id="pais" name="Pais" class="select">
                                </select>
                            </div>
                            <script type="text/javascript">
                                //la funcion llamada esta en el js cargar_contenido - carpeta public
                                cargarContenido('<?php echo $this->url(array('controller' => 'location', 'action' => 'country', 'obligatorio' => '0'), null, true) ?>', 'div_pais')
                            </script>
                            <div id="div_estado" style="float: left; padding-right:7px;">
                                <select data-placeholder="Estado" id="estado" name="Estado" style="width: 116px;" class="select">
                                </select>
                            </div>
                            <div id="div_ciudad"  style="float: left;">
                                <select data-placeholder="Ciudad" id="ciudad" style="width: 116px;" name="Ciudad" class="select">>
                                </select>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align: center; padding-top: 5px; width: 400px; padding-right: 10px;">
                        <input type="submit" value="Ingresar" class="button_submit"/>        
                    </td>
                </tr>
            </table>
        </div>


        <script type="text/javascript" >
            $(".select").chosen()
        </script>
    </form>
</div>