<form id="form" class="remember" onsubmit="return login('<?php echo $this->url(array('controller' => 'register', 'action' => 'login'), null, true); ?>')">
    <h1>Arango</h1>
    <fieldset id="inputsNewUser">
        <input id="email" type="email" placeholder="Email" autofocus="" required="">   
    </fieldset>
    <fieldset id="actions">
        <input type="submit" id="submit" value="Recuerdame">
        <a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'login'), null, true); ?>">Recuerdas tu clave?, Ingresa aqui</a><a id="registerLink" href="<?php echo $this->url(array('controller' => 'register', 'action' => 'newuser'), null, true); ?>">Registrate</a>
    </fieldset>
</form>