<section class="container">
    <div class="page-header" >
    <h1>Biblioteca, Familia Arango Medina Eeeee ome ssssss</h1>
    <p>En el formato de abajo ingrese el nombre. Posibles nombres
        pareceran debajo del formato.</p>
    </div>
    <div id="imagen_principal" ><img src="<?php echo $this->baseUrl('public/Images/alejoLeyendo.jpg') ?>" width="700" height="273" alt="alejoLeyendo"/></div>
</section>