<div>
    <div class="izq-header">
        <label style="font-family: JUICEBold;font-size: 14px;">¡Creyendo!</label>
    </div>
    <!--<div id="imagen_principal" style="float: right; text-align: right;"><img src="<?php echo $this->baseUrl('Images/alejoLeyendo.jpg') ?>" width="700" height="273" alt="alejoLeyendo"/></div>-->
    <header class="page-header" >
            <div style="float: left; text-align: right;"><h1>Biblioteca</h1></div>
            <div style="float: left;"><h2>Arango</h2></div>
            <div class="imagen_alejo" ><img src="<?php echo $this->baseUrl('Images/alejoLeyendo.png') ?>"alt="alejoLeyendo"/></div>
            <div class="clear"> </div>
    </header>
</div>

