<div>
    <div class="izq-header" style="display: none;">
        <label style="font-family: JUICEBold;font-size: 14px;">¡Creyendo!</label>
    </div>
    <!--<div id="imagen_principal" style="float: right; text-align: right;"><img src="<?php echo $this->baseUrl('Images/alejoLeyendo.jpg') ?>" width="700" height="273" alt="alejoLeyendo"/></div>-->
    <header class="page-header" >
        <div class="tittle_holder">
            <div style="float: left; text-align: right;"><h1>Biblioteca</h1></div>
            <div style="float: left;"><h2>Arango</h2></div>
            <div class="imagen_alejo" ><img src="<?php echo $this->baseUrl('Images/layout/alejoLeyendo.png') ?>"alt="alejoLeyendo"/></div>
            <!--<div class="clear"> </div>-->
        </div>
        <div style="" onmouseover=""></div>
        <nav class="nav_top" >
            <ul>
                <li><a href="#">Casa</a></li>
                <li><a href="#">Libros</a></li>
                <li><a href="#">Autores</a></li>
                <li><a href="#">Editoriales</a></li>
                <li><a href="#">Lo último</a></li>
                <li><a href="#">¿Quién?</a></li>
            </ul>
        </nav>

    </header>
</div>

