<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>

        <?php
        echo $this->headLink()->appendStylesheet($this->baseUrl('css/fonts.css'))
                ->appendStylesheet($this->baseUrl('css/stylesheet.css'))
                ->appendStylesheet($this->baseUrl('css/chosen.css'));
        ?>

        <?php
        echo $this->headScript()->appendFile($this->baseUrl('js/general/cargar_contenido.js'))
                ->appendFile($this->baseUrl('js/general/ajax.js'))
                ->appendFile($this->baseUrl('js/general/funciones.js'))
                ->appendFile($this->baseUrl('js/general/app.js'))
                ->appendFile($this->baseUrl('js/resources/jquery.tools.min.js'))
                ->appendFile($this->baseUrl('js/resources/chosen.jquery.min.js'));
        ?>

        <link href='http://fonts.googleapis.com/css?family=Podkova' rel='stylesheet' type='text/css'>
    </head>

    <body>



        <!--S E S S I O N-->
        <?php
        $usuarioLogeado = new Zend_Session_Namespace("usuarioLogeado");
        ?>

        <!--H E A D E R-->
        <div>
            <?php echo $this->render('header.phtml'); ?>
        </div>

        <div class="separador_y"></div>

        <!--COLUMNA DE CONTENIDOS-->
        <div class="">
            <section class="container">
                <div class="section">
                    <?php
                    echo $this->layout()->content;
                    ?>
                </div>
            </section>

        </div>


        <!--FOOTER-->
        <div>
            <?php echo $this->render('footer.phtml'); ?>
        </div>


        <!-- BODY BORDER -->
        <div class="edge" id="left_body_border"></div>
        <div class="edge" id="right_body_border"></div>
        <div class="edge" id="top_body_border"></div>
        <div class="edge" id="bottom_body_border"></div>
        <script type="text/javascript">
            $(document).ready(function() {
                $(function(){
                    $(".nav_top").click(function(){
                        $(".edge").fadeToggle();
                    });
                });
            });
            
        </script>
    </body>

</html>
