<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('css/stylesheet.css')); ?>


    </head>

<body>



    <!--S E S S I O N-->
    <?php
        $usuarioLogeado = new Zend_Session_Namespace("usuarioLogeado");
        
    ?>

    <!--H E A D E R-->
    <?php echo $this->render('header.phtml'); ?>
    
    


        <!--COLUMNA DE CONTENIDOS-->
        <div class="colum_medio">
                <?php
                    echo $this->layout()->content;
                ?>

        </div>


    <!--FOOTER-->
    <?php echo $this->render('footer.phtml'); ?>

    
</body>

</html>
