<html>
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <?php
        echo $this->headScript()->appendFile($this->baseUrl('js/resources/jquery-1.7.1.min.js'))
                ->appendFile($this->baseUrl('js/resources/jquery.noty.js'))
                ->appendFile($this->baseUrl('js/resources/chosen.jquery.min.js'))
                ->appendFile($this->baseUrl('js/resources/jquery.form.js'))
                ->appendFile($this->baseUrl('js/general/cargar_contenido.js'))
                ->appendFile($this->baseUrl('js/general/funciones.js'))
                ->appendFile($this->baseUrl('js/general/login.js'));
        ?>
        <?php
        echo $this->headLink()->appendStylesheet($this->baseUrl('css/fonts.css'))
                ->appendStylesheet($this->baseUrl('css/jquery.noty.css'))
                ->appendStylesheet($this->baseUrl('css/error.css'))        
                ->appendStylesheet($this->baseUrl('css/login.css'));
        ?>
    </head>

    <body>


        <div id="form_wrapper" class="login">
            <?php echo $this->layout()->content; ?>
        </div>

        <div id="nextForm" style="display:none;">

        </div>

        <!-- BODY BORDER -->
        <div class="edge" id="left_body_border"></div>
        <div class="edge" id="right_body_border"></div>
        <!--<div class="edge" id="top_body_border"></div>-->
        <div class="edge" id="bottom_body_border"></div>
        <script type="text/javascript">
            $(document).ready(function() {
                
                var classTemp = $("#form").attr("class");
                $("#form").removeClass();
                $("#form_wrapper").addClass(classTemp);
                
            });
            
        </script>


    </body>
</html>